### ISSUE TITLE
Setup scroll view default index as Card List item click position

### ISSUE THREAD

**Issue by GarimaMathur07** [browniefed/map_animated_scrollview#1]
@browniefed Can we setup scroll view default index as List item click position because i want to open map animated scroll view as per List view item click.

  ```
componentWillMount() {
    this.index = 0; // should be not always first index, it can be dynamic value as per list item click 
    this.animation = new Animated.Value(0);
  }
```
@browniefed can you please provide the solution because i have tried with set dynamic value in `this.index`but it is not working.

**Comment by browniefed** [comment]
Are you trying to say you want to have the list of items be selectable? I would potentially swap it out for something like https://github.com/kkemple/react-native-sideswipe if you want that functionality
